### PR TITLE
Version bump for 3.0.0-ALPHA10

### PR DESCRIPTION
**Pull request by dirouc**

### CODE REVIEW

**Comment by dktapps** [comment]
ALPHA10 isn't tagged yet. You have no idea if this plugin is actually compatible or not.

**Comment by dirouc** [comment]
@dktapps I'll let you know.

**Comment by dirouc** [comment]
Everything works fine.

**Comment by dktapps** [comment]
Are you stupid? *ALPHA10 is not tagged*, therefore it is not finalised, therefore you cannot judge it to be compatible.

**Comment by dirouc** [comment]
And the sense then is to change it in pmmp, if it is not ready even, would have done, then would have installed.

**Comment by dirouc** [comment]
Change the constant, and then do it, ingeniously.

**Comment by dktapps** [comment]
You're not supposed to be using the master branch because it's bleeding edge. You're supposed to use tagged releases.

**Comment by dirouc** [comment]
@dktapps What should I use on your local server?

**Comment by dirouc** [comment]
Stable version https://jenkins.pmmp.io/job/PocketMine-MP/Stable/ not found.

**Pull request merged**
